server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ipay-service
          uri: http://localhost:8081
          predicates:
            - Path=/ipay/**
        - id: ibanking-service
          uri: http://localhost:8082
          predicates:
            - Path=/ibanking/**
        - id: shop-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/shop/**

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: yourSecretKeyHereMustBeVeryLongAndSecure
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

# Configuration pour SpringDoc OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    enabled: true
    config-url: /v3/api-docs/swagger-config
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    default-models-expand-depth: -1
    urls:
      - url: /v3/api-docs
        name: API Gateway
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: true
  packages-to-scan: com.innov4africa.api_gateway.controller
  paths-to-match: 
    - /ishop/**
    - /ipay/**
    - /ibanking/**
    - /auth/**
    - /wave/**
    - /orange-money/**

# Configuration URLs for OpenAPI
openapi:
  dev-url: http://localhost:8080
  prod-url: https://api.innov4africa.sn

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://137.184.94.79:8443/auth}
  realm: ${KEYCLOAK_REALM:Ibanking}
  resource: ${KEYCLOAK_CLIENT_ID:ibanking-backoffice}
  public-client: true
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: external
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

# Configuration des services externes
ishop:
  base-url: https://ibusinesscompanies.com:8443
