# Disable Spring Cloud compatibility check temporarily
spring.cloud.compatibility-verifier.enabled=false

# Web application type
spring.main.web-application-type=reactive

# Logging configuration
logging.level.org.springframework.ws=TRACE
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.soap=TRACE

logging.level.org.springframework=DEBUG
logging.level.org.glassfish.jaxb=DEBUG
logging.level.org.springframework.oxm.jaxb.Jaxb2Marshaller=DEBUG

# Ajout de logs détaillés pour le client HTTP
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE
logging.level.reactor.netty.http.client=DEBUG
logging.level.io.netty=DEBUG

# Configuration pour iSwitch/Wave
iswitch.api.url=https://ibusinesscompanies.com:8443/iswitch-ws
wave.membre.payeur=SN001
wave.membre.paye=SN005

# Configuration i-shop
ishop.base-url=https://ibusinesscompanies.com:8443


# application.properties
spring.codec.max-in-memory-size=16MB
